name: Jest Tests

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**' 
      - '!main'
      - '!staging'
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**' 
      - '!main'
      - '!staging'
jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.10.0]
    steps:
    - uses: actions/checkout@v4
    
    - uses: pnpm/action-setup@v2
      with:
        version: "8.11.0"
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run linter checks
      run: npm run lint

    - name: Run Jest tests
      run: npm run test

    - name: Setup Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 

    - name: Create .env file
      run: |
        echo "VITE_KINDE_CLIENT_ID=${{ vars.VITE_KINDE_CLIENT_ID }}" >> .env
        echo "VITE_KINDE_DOMAIN=${{ vars.VITE_KINDE_DOMAIN }}" >> .env
        echo "VITE_KINDE_LOGOUT_URI=${{ vars.VITE_KINDE_LOGOUT_URI }}" >> .env
        echo "VITE_KINDE_REDIRECT_URI=${{ vars.VITE_KINDE_REDIRECT_URI }}" >> .env
        echo "VITE_STREAMLINE_SERVICES_URL=${{ vars.VITE_STREAMLINE_SERVICES_URL }}" >> .env

    - name: Remove previous chrome instances
      run: sudo apt purge google-chrome-stable

    - name: Install Selenium
      run: pip install chromedriver-autoinstaller selenium pyvirtualdisplay

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Run Selenium tests
      run: |
         npm run dev &
         npm run test:e2e
      shell: bash

    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Deploy to Google cloud Storage
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: dist
        destination: streamline-web
        parent: false

    - name: Publicly Accessible URL
      run: echo "https://streamline-web.storage.googleapis.com"
